apiVersion: v1
kind: Service
metadata:
  name: booking-backend-service
  labels:
    app: booking-backend
spec:
  type: ClusterIP
  selector:
    app: booking-backend
  ports:
    - port: 5000
      targetPort: 5000